apiVersion: v1
kind: Service
metadata:
  labels:
    app: demo
  name: demo-service
  namespace: default
spec:
  type: NodePort
  ports:
  - name: webport
    port: 80
    targetPort: 80
    nodePort: 31111
  selector:
    app: demo
